apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  valuesContent: |
    server:
      insecure: true
      service:
        type: NodePort
        nodePortHttp: 30080
        nodePortHttps: 30443

    configs:
      secret:
        # The password is 'admin' for the argocd-server-admin secret
        argocdServerAdminPassword: $2a$10$8oMaaRD4E0zpuoQ9TaF/.eDyS9iGhqhpr6q6vJL3qytskO2KkoIL6

