apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kiali-server
  namespace: kube-system
spec:
  repo: https://kiali.org/helm-charts
  chart: kiali-server
  targetNamespace: istio-system
  valuesContent: |
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: "prometheus-stack-kube-prometheus-prometheus.monitoring.svc:9090"


---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
  - "kiali.localhost"
  gateways:
  - istio-ingress/istio-ingress-gateway
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001
