apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  releaseName: prometheus-stack
  valuesContent: |
    prometheus:
      prometheusSpec:
        service:
          type: NodePort
          nodePort: 30900  # Adjust if needed
        serviceMonitorSelectorNilUsesHelmValues: false
    alertmanager:
      alertmanagerSpec:
        service:
          type: NodePort
          nodePort: 30903  # Adjust if needed
    grafana:
      service:
        type: NodePort
        nodePort: 30902  # Adjust if needed
    # Enable persistence if needed
    prometheusOperator:
      createCustomResource: true
